import React, { Component } from 'react'
import aboutImg1 from '../asset/img/about1.png'
import aboutImg2 from '../asset/img/about2.png'
import aboutImg3 from '../asset/img/about3.png'
import aboutImg4 from '../asset/img/about4.png'
import aboutImg5 from '../asset/img/about5.png'
import aboutImg6 from '../asset/img/about6.png'
import keyInfoImg1 from '../asset/img/key_info_first.png'
import keyInfoImg2 from '../asset/img/keyinfo_pricing.png'
import keyInfoImg3 from '../asset/img/key_info_eth.png'


export default class About extends Component {
    render() {
        const aboutimgs = [aboutImg1, aboutImg2, aboutImg3, aboutImg4, aboutImg5, aboutImg6];
        const keyInfoImgs = [keyInfoImg1, keyInfoImg2, keyInfoImg3];
        let keyInfoHelp1 = "4,200 Unique Bongs with more than 100+ traits and differentrarities.";
        let keyInfoHelp2 = "Pricing: 0.042 ETH flat price to give everybody a fair chance to join the club and take a hit!";
        let keyInfoHelp3 = "Our ERC-721 NFT’s come with full ownership and commercial usage rights and other cool utilities still to be announced!!";
        const keyInfoDes = [keyInfoHelp1, keyInfoHelp2, keyInfoHelp3];
        return (
            <div className="text-center bg-gray-100 py-5">
                <div>
                    <div className="text-black">
                        <span className="text-4xl font-bold">
                            ABOUT US
                        </span>
                        <div className="flex justify-center">
                            <p className="text-lg mt-3 w-9/12">
                                The Crazy Bong Club is 4200 Fun and Crazy Bongs programmatically
                                generated by a random combination of hundreds of traits! These
                                artworks live on the Ethereum blockchain in form of ERC-721 tokens.
                                Crazy Bongs will be sold for .0420 each! Our club is of course focused
                                on our love for Weed and other 420 related items! We have some crazy
                                cool items in our roadmap which is all laid out below! DID we mention
                                one of the BONGS will be the image for Ape #4434 and IF you hold that
                                item you will WIN that ape!! Check out our Twitter and Discord Links
                                below for more info on Launch Date and Follow us for a Daily Free
                                Giveaways up till launch!!
                            </p>
                        </div>
                    </div>
                    <div className="flex justify-start mt-5 px-5">
                        {aboutimgs.map( (aboutArt, index) => {
                            return (
                                <div className="p-2 w-1/6" key={index}>
                                    <img src={aboutArt}></img>
                                </div>
                            );
                        })}
                    </div>
                </div>
                <div className="mt-5">
                    <div className="text-black">
                        <span className="text-3xl">
                            KEY INFORMATION
                        </span>
                    </div>
                    <div className="flex justify-center px-10 mt-3">
                        {keyInfoImgs.map( (keyInfoArt, index) => {
                            return (
                                <div className="px-10 w-1/3 flex justify-center" key={index}>
                                    <div>
                                        <img src={keyInfoArt}></img>
                                        <p className="text-lg mt-3">
                                            {keyInfoDes[index]}
                                        </p>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        )
    }
}
