import React, { Component } from 'react'
import Timeline from '@material-ui/lab/Timeline';
import TimelineItem from '@material-ui/lab/TimelineItem';
import TimelineSeparator from '@material-ui/lab/TimelineSeparator';
import TimelineConnector from '@material-ui/lab/TimelineConnector';
import TimelineContent from '@material-ui/lab/TimelineContent';
import TimelineDot from '@material-ui/lab/TimelineDot';
// import Paper from '@material-ui/core/Paper';

import roadmapImg1 from '../asset/img/roadmap1.png'
import roadmapImg2 from '../asset/img/roadmap2.png'
import roadmapImg3 from '../asset/img/roadmap3.png'
import roadmapImg4 from '../asset/img/roadmap4.png'
import roadmapImg5 from '../asset/img/roadmap5.png'

  
export default class Loadmap extends Component {
    render() {
        const roadmapImgs = [roadmapImg1, roadmapImg2, roadmapImg3, roadmapImg4, roadmapImg5];
        let roadmapTitle1   = "Launch:";
        let roadmapSubTxt1  = "4200 Fun and Crazy Bongs programmatically generated by a random combination of hundreds of traits! These artworks live on the Ethereum blockchain in form of ERC-721 tokens. Crazy Bongs will be sold for .0420 each!...";
        let roadmapTitle2   = "25% Sold:";
        let roadmapSubTxt2  = "4.20 ETH will be given away to random Wallet/Wallets! We will allow our community to vote before payments are sent if we will send 1 payment of 4.20 or 10 at .420 each!"
        let roadmapTitle3   = "50% Sold:";
        let roadmapSubTxt3  = "Ape #4434 Image will randomly be inserted as a replacement NFT, this is redeemable for The Professional Pothead Bored Ape #4434!!!"
        let roadmapTitle4   = "75% Sold:";
        let roadmapSubTxt4  = "Crazy Bongs Store Opens! We will drop some crazy exclusive T-shirts for our bongs and other NFT related items that users can resell or redeem for actual products!"
        let roadmapTitle5   = "100% Sold:";
        let roadmapSubTxt5  = "ONE Lucky winner ANYWHERE WORLDWIDE will win a Fully Paid Trip to Washington, DC to Visit a Dispensary in DC in person!!! Trip includes paid airfare, lodging and $1000.00 in spending cash for your visit to DC! (Please note we are not responsible if winner does not have needed passports/visa to enter the country we will not be able to provide any assistant in these matters.)"
        const roadmapTitles     = [roadmapTitle1, roadmapTitle2, roadmapTitle3, roadmapTitle4, roadmapTitle5];
        const roadmapSubTxts    = [roadmapSubTxt1, roadmapSubTxt2, roadmapSubTxt3, roadmapSubTxt4, roadmapSubTxt5]
        return (
            <div className="text-center py-5 mb-10">
                <div className="text-black">
                    <span className="text-4xl font-bold">
                        ROADMAP
                    </span>
                </div>
                <div className="flex justify-center">
                    <div className="w-4/5">
                        <Timeline align="alternate">
                            <TimelineItem className="min-h-0">
                            </TimelineItem>
                            {roadmapImgs.map( (roadmapArt, index) => {
                                return (
                                    <TimelineItem className="" key={index}>
                                        <TimelineSeparator >
                                            <TimelineDot className="w-40">
                                                <img className="rounded-full" src={roadmapArt}></img>
                                            </TimelineDot>
                                            {(index<roadmapImgs.length-1)&&(<TimelineConnector className="h-20"/>)}
                                            
                                        </TimelineSeparator>
                                        <TimelineContent>
                                            <div className={`mt-2 ${index % 2 == 1 ? "text-left ml-10" : "text-right mr-10"}`}>
                                                <p className="text-2xl font-bold">
                                                    {roadmapTitles[index]}
                                                </p>
                                                <p className="text-lg">
                                                    {roadmapSubTxts[index]}
                                                </p>
                                            </div>
                                        </TimelineContent>
                                    </TimelineItem>
                                );
                            })}
                            
                        </Timeline>
                    </div>
                </div>
            </div>
        )
    }
}
